# Generated by Django 5.2.17 on 2026-08-31 19:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ledger", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="user",
            options={},
        ),
        migrations.AddField(
            model_name="user",
            name="scim_external_id",
            field=models.CharField(
                blank=True,
                db_index=True,
                default=None,
                help_text="A string that is an identifier for the resource as defined by the provisioning client.",
                max_length=254,
                null=True,
                verbose_name="SCIM External ID",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="scim_id",
            field=models.CharField(
                blank=True,
                default=None,
                help_text="A unique identifier for a SCIM resource as defined by the service provider.",
                max_length=254,
                null=True,
                unique=True,
                verbose_name="SCIM ID",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="scim_username",
            field=models.CharField(
                blank=True,
                db_index=True,
                default=None,
                help_text="A service provider's unique identifier for the user",
                max_length=254,
                null=True,
                verbose_name="SCIM Username",
            ),
        ),
    ]
