# Generated by Django 5.2.17 on 2026-08-31 21:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ledger", "0002_alter_user_options_user_scim_external_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="grant",
            name="source_key",
            field=models.CharField(blank=True, editable=False, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name="sale",
            name="source_key",
            field=models.CharField(blank=True, editable=False, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name="vest",
            name="source_key",
            field=models.CharField(blank=True, editable=False, max_length=64, null=True),
        ),
        migrations.AddConstraint(
            model_name="grant",
            constraint=models.UniqueConstraint(
                condition=models.Q(("source_key__isnull", False)),
                fields=("workspace", "source_key"),
                name="unique_imported_grant",
            ),
        ),
        migrations.AddConstraint(
            model_name="sale",
            constraint=models.UniqueConstraint(
                condition=models.Q(("source_key__isnull", False)),
                fields=("workspace", "source_key"),
                name="unique_imported_sale",
            ),
        ),
        migrations.AddConstraint(
            model_name="vest",
            constraint=models.UniqueConstraint(
                condition=models.Q(("source_key__isnull", False)),
                fields=("workspace", "source_key"),
                name="unique_imported_vest",
            ),
        ),
    ]
