# Generated by Django 5.2.17 on 2026-08-31 21:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ledger", "0003_grant_source_key_sale_source_key_vest_source_key_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fxrate",
            name="method",
            field=models.CharField(
                choices=[
                    ("spot", "HMRC spot"),
                    ("monthly", "HMRC monthly"),
                    ("average", "HMRC average"),
                    ("wise", "Wise historical spot"),
                ],
                max_length=20,
            ),
        ),
    ]
