# Generated by Django 5.2.17 on 2026-08-31 21:35

import django.db.models.deletion
from django.db import migrations, models
from django.db.models.functions import Lower


def create_default_brokers(apps, schema_editor):
    workspace_model = apps.get_model("ledger", "Workspace")
    broker_model = apps.get_model("ledger", "Broker")
    for workspace in workspace_model.objects.iterator():
        for name in ("Morgan Stanley E*TRADE", "Charles Schwab"):
            broker_model.objects.get_or_create(workspace=workspace, name=name)


def remove_default_brokers(apps, schema_editor):
    broker_model = apps.get_model("ledger", "Broker")
    broker_model.objects.filter(name__in=("Morgan Stanley E*TRADE", "Charles Schwab")).delete()


class Migration(migrations.Migration):
    dependencies = [
        ("ledger", "0004_alter_fxrate_method"),
    ]

    operations = [
        migrations.AddField(
            model_name="grant",
            name="grant_id",
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name="sale",
            name="grant_id",
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name="vest",
            name="grant_id",
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.CreateModel(
            name="Broker",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                (
                    "workspace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="brokers",
                        to="ledger.workspace",
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.AddField(
            model_name="grant",
            name="broker",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="ledger.broker",
            ),
        ),
        migrations.AddField(
            model_name="sale",
            name="broker",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="ledger.broker",
            ),
        ),
        migrations.AddField(
            model_name="vest",
            name="broker",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="ledger.broker",
            ),
        ),
        migrations.AddConstraint(
            model_name="broker",
            constraint=models.UniqueConstraint(
                Lower("name"), "workspace", name="unique_workspace_broker"
            ),
        ),
        migrations.RunPython(create_default_brokers, remove_default_brokers),
    ]
