# Generated by Django 5.2.17 on 2026-08-31 22:05

from decimal import Decimal

from django.db import migrations, models


def migrate_legacy_event_rates(apps, schema_editor):
    fx_rate_model = apps.get_model("ledger", "FxRate")
    for model_name in ("Grant", "Vest", "Sale"):
        record_model = apps.get_model("ledger", model_name)
        for record in record_model.objects.filter(gbp_per_usd__isnull=False).iterator():
            if fx_rate_model.objects.filter(
                workspace_id=record.workspace_id,
                starts_on__lte=record.date,
                ends_on__gte=record.date,
            ).exists():
                continue
            fx_rate_model.objects.create(
                workspace_id=record.workspace_id,
                label=f"Migrated legacy event rate for {record.date.isoformat()}",
                method="manual",
                starts_on=record.date,
                ends_on=record.date,
                usd_per_gbp=Decimal(1) / record.gbp_per_usd,
                source_url="https://example.invalid/legacy-event-rate",
            )


class Migration(migrations.Migration):
    dependencies = [
        ("ledger", "0005_grant_grant_id_sale_grant_id_vest_grant_id_broker_and_more"),
    ]

    operations = [
        migrations.RunPython(migrate_legacy_event_rates, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name="grant",
            name="gbp_per_usd",
        ),
        migrations.RemoveField(
            model_name="sale",
            name="gbp_per_usd",
        ),
        migrations.RemoveField(
            model_name="vest",
            name="gbp_per_usd",
        ),
        migrations.AlterField(
            model_name="fxrate",
            name="method",
            field=models.CharField(
                choices=[
                    ("spot", "HMRC spot"),
                    ("monthly", "HMRC monthly"),
                    ("average", "HMRC average"),
                    ("wise", "Wise historical spot"),
                    ("manual", "Manual or migrated rate"),
                ],
                max_length=20,
            ),
        ),
    ]
