# Generated by Django 5.2.17 on 2026-08-31 22:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ledger", "0006_remove_grant_gbp_per_usd_remove_sale_gbp_per_usd_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="grant",
            name="ticker",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.CreateModel(
            name="StockPrice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("ticker", models.CharField(max_length=20)),
                ("price_date", models.DateField()),
                ("usd_price", models.DecimalField(decimal_places=6, max_digits=16)),
                (
                    "source",
                    models.CharField(
                        choices=[("manual", "Manual"), ("finnhub", "Finnhub live quote")],
                        default="manual",
                        max_length=20,
                    ),
                ),
                ("fetched_at", models.DateTimeField(blank=True, null=True)),
                ("source_url", models.URLField(blank=True)),
                ("notes", models.TextField(blank=True)),
                (
                    "workspace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stock_prices",
                        to="ledger.workspace",
                    ),
                ),
            ],
            options={
                "ordering": ["ticker", "-price_date"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("workspace", "ticker", "price_date", "source"),
                        name="unique_workspace_ticker_price_date_source",
                    )
                ],
            },
        ),
    ]
