# Generated by Django 5.2.17 on 2026-09-01 06:37

import django.db.models.deletion
from django.db import migrations, models


def link_existing_grants_to_securities(apps, schema_editor):
    grant_model = apps.get_model("ledger", "Grant")
    security_model = apps.get_model("ledger", "Security")
    for grant in grant_model.objects.exclude(ticker="").iterator():
        security, _ = security_model.objects.get_or_create(
            workspace_id=grant.workspace_id,
            ticker=grant.ticker,
            share_class="",
            defaults={"name": grant.ticker},
        )
        grant.security_id = security.id
        grant.save(update_fields=["security"])


class Migration(migrations.Migration):
    dependencies = [
        ("ledger", "0007_grant_ticker_stockprice"),
    ]

    operations = [
        migrations.CreateModel(
            name="Security",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=160)),
                ("ticker", models.CharField(max_length=20)),
                ("isin", models.CharField(blank=True, max_length=12)),
                ("share_class", models.CharField(blank=True, max_length=80)),
                (
                    "workspace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="securities",
                        to="ledger.workspace",
                    ),
                ),
            ],
            options={
                "ordering": ["ticker", "share_class", "name"],
            },
        ),
        migrations.AddField(
            model_name="grant",
            name="security",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="ledger.security",
            ),
        ),
        migrations.AddConstraint(
            model_name="security",
            constraint=models.UniqueConstraint(
                fields=("workspace", "ticker", "share_class"),
                name="unique_workspace_security_share_class",
            ),
        ),
        migrations.RunPython(link_existing_grants_to_securities, migrations.RunPython.noop),
    ]
