name: Unified Python CI

on:
  push:
    branches: [main]
  pull_request:

jobs:
  quality:
    uses: git.tainton.uk/actions/gha-workflows/.gitea/workflows/ci-python-uv-with-docker.yml@main
    with:
      python-version: "3.13"
