import './style.css';

const KEY = 'rsu-ledger-uk-v1';
const example = { company: 'Acme Networks', ticker: 'ACME', grants: [{id:'g1', date:'2024-02-14', units:480, note:'FY24 new-hire grant'}], vests: [{id:'v1', grantId:'g1', date:'2025-02-14', units:120, usd:158.42, fx:0.7921, withheld:47, incomeTax:5301.34, nic:204.53, fees:0, source:'Payslip / broker confirmation'}], sales: [{id:'s1', date:'2025-04-21', units:35, usd:171.28, fx:0.7462, fees:8.95, note:'Diversification sale'}] };
let state = JSON.parse(localStorage.getItem(KEY) || 'null') || structuredClone(example);
const money = n => new Intl.NumberFormat('en-GB',{style:'currency',currency:'GBP',maximumFractionDigits:2}).format(n || 0);
const num = n => Number(n || 0);
const fmt = d => d ? new Intl.DateTimeFormat('en-GB',{dateStyle:'medium'}).format(new Date(`${d}T00:00:00`)) : '—';
const gbp = (usd,fx) => num(usd) * num(fx);
const taxYear = date => { const d=new Date(`${date}T00:00:00`), y=d.getFullYear(); return d >= new Date(y,3,6) ? `${y}/${String(y+1).slice(2)}` : `${y-1}/${String(y).slice(2)}`; };
const save = () => localStorage.setItem(KEY, JSON.stringify(state));
const byDate = a => [...a].sort((x,y)=>x.date.localeCompare(y.date));

function vestValue(v){ return v.units * gbp(v.usd,v.fx); }
function totalHeld(){return state.vests.reduce((s,v)=>s+num(v.units)-num(v.withheld),0)-state.sales.reduce((s,v)=>s+num(v.units),0)}

// UK CGT share identification: same day, then acquisitions in next 30 days, then Section 104 pool.
function calculateCGT(){
 const vests = byDate(state.vests).map(v=>({...v, remaining:num(v.units)-num(v.withheld), cost:vestValue(v)}));
 const sales = byDate(state.sales); let rows=[];
 for(const sale of sales){
  let remaining=num(sale.units), cost=0, matches=[]; const proceeds=remaining*gbp(sale.usd,sale.fx)-num(sale.fees);
  const use=(v,q,label)=>{ const unit=v.cost/(num(v.units)-num(v.withheld)); cost+=q*unit; v.remaining-=q; matches.push(`${q} ${label}`); remaining-=q; };
  for(const v of vests.filter(v=>v.date===sale.date&&v.remaining>0)){ if(!remaining)break;use(v,Math.min(remaining,v.remaining),'same day'); }
  const after=new Date(`${sale.date}T00:00:00`); for(const v of vests.filter(v=>{const days=(new Date(`${v.date}T00:00:00`)-after)/86400000;return days>0&&days<=30&&v.remaining>0})){if(!remaining)break;use(v,Math.min(remaining,v.remaining),'within 30 days');}
  if(remaining){ const prior=vests.filter(v=>v.date<sale.date&&v.remaining>0); const poolUnits=prior.reduce((s,v)=>s+v.remaining,0), poolCost=prior.reduce((s,v)=>s+v.remaining*(v.cost/(num(v.units)-num(v.withheld))),0); const q=Math.min(remaining,poolUnits); if(q){const unit=poolCost/poolUnits; cost+=q*unit; let consume=q; for(const v of prior){const take=Math.min(consume,v.remaining);v.remaining-=take;consume-=take;}matches.push(`${q} Section 104 pool`);remaining-=q;} }
  rows.push({sale,proceeds,cost,gain:proceeds-cost,unmatched:remaining,matches:matches.join(' · ')||'No matching acquisition'});
 }
 return rows;
}
function stats(){ const cgt=calculateCGT(); return {vested:state.vests.reduce((s,v)=>s+vestValue(v),0), tax:state.vests.reduce((s,v)=>s+num(v.incomeTax)+num(v.nic),0), proceeds:state.sales.reduce((s,v)=>s+v.units*gbp(v.usd,v.fx)-num(v.fees),0), gains:cgt.reduce((s,x)=>s+x.gain,0), held:totalHeld()}; }

function form(kind){
 const labels={grant:'Add grant',vest:'Record vest',sale:'Record sale'}; const fields={
 grant:[['date','Grant date','date'],['units','Units awarded','number'],['note','Reference / notes','text']],
 vest:[['date','Vest date','date'],['units','Gross units vested','number'],['usd','USD share price','number'],['fx','GBP per USD exchange rate','number'],['withheld','Shares withheld/sold for tax','number'],['incomeTax','Income Tax withheld (GBP)','number'],['nic','Employee NIC withheld (GBP)','number'],['fees','Broker fees (GBP)','number'],['source','Evidence / valuation source','text']],
 sale:[['date','Trade date','date'],['units','Shares sold','number'],['usd','USD price per share','number'],['fx','GBP per USD exchange rate','number'],['fees','Selling fees (GBP)','number'],['note','Reference / notes','text']]
 }[kind];
 return `<dialog class="modal" id="entryModal"><form method="dialog" id="entryForm"><div class="modal-head"><h2>${labels[kind]}</h2><button class="icon" value="cancel">×</button></div>${kind==='vest'?`<p class="help">Use the actual taxable market value and PAYE figures from your employer/broker records.</p>`:''}${fields.map(([name,label,type])=>`<label>${label}<input required=${!['withheld','incomeTax','nic','fees','note','source'].includes(name)} name="${name}" type="${type}" step="${type==='number'?'any':''}" min="0"></label>`).join('')}<div class="form-actions"><button class="ghost" value="cancel">Cancel</button><button class="primary" value="default">Save ${kind}</button></div></form></dialog>`;
}
function render(){ const s=stats(), cgt=calculateCGT(); document.querySelector('#app').innerHTML=`
<main><nav><div class="brand"><span>R</span><div>RSU Ledger <small>UK</small></div></div><div class="nav-actions"><button data-action="export" class="ghost">Export CSV</button><button data-action="reset" class="ghost danger">Reset demo</button></div></nav>
<section class="hero"><div><p class="eyebrow">PERSONAL EQUITY LEDGER</p><h1>Know your real <em>sterling</em> position.</h1><p class="lead">A private record of awards, taxable vesting events and sales—built around the UK CGT trail.</p></div><div class="company"><label>Company<input id="company" value="${state.company||''}" placeholder="e.g. Cisco Systems"></label><label>Ticker<input id="ticker" value="${state.ticker||''}" placeholder="e.g. CSCO"></label></div></section>
<section class="cards"><article><span>Current holding</span><strong>${s.held.toLocaleString()} shares</strong><small>Net of tax withholding and sales</small></article><article><span>Vested value</span><strong>${money(s.vested)}</strong><small>At vest-date GBP value</small></article><article><span>CGT gain / (loss)</span><strong class="${s.gains<0?'negative':''}">${money(s.gains)}</strong><small>Across recorded disposals</small></article><article><span>PAYE & NIC tracked</span><strong>${money(s.tax)}</strong><small>Employer / broker reported deductions</small></article></section>
<section class="workspace"><div class="ledger"><div class="section-head"><div><p class="eyebrow">ACTIVITY</p><h2>Your ledger</h2></div><div class="buttons"><button data-form="grant" class="ghost">+ Grant</button><button data-form="vest" class="primary">+ Vest</button><button data-form="sale" class="ghost">+ Sale</button></div></div><div class="timeline">${[...state.grants.map(x=>({...x,type:'Grant'})),...state.vests.map(x=>({...x,type:'Vest'})),...state.sales.map(x=>({...x,type:'Sale'}))].sort((a,b)=>b.date.localeCompare(a.date)).map(x=>`<div class="event"><div class="date">${fmt(x.date)}<small>${taxYear(x.date)}</small></div><div class="dot ${x.type.toLowerCase()}"></div><div><b>${x.type}</b><p>${x.units} ${x.type==='Grant'?'units awarded':x.type==='Vest'?`units · ${money(vestValue(x))} taxable value`:`shares · ${money(x.units*gbp(x.usd,x.fx)-num(x.fees))} proceeds`}</p></div><button class="delete" data-delete="${x.type.toLowerCase()}:${x.id}">Delete</button></div>`).join('')||'<p class="empty">No entries yet.</p>'}</div></div>
<aside><p class="eyebrow">CGT CHECK</p><h2>Disposals</h2><p class="help">Estimate only. It applies UK ordering: same-day, next 30 days, then Section 104 pool. Verify against your full share history.</p>${cgt.length?cgt.map(x=>`<div class="cgt-row"><div><b>${fmt(x.sale.date)}</b><small>${x.matches}</small></div><strong class="${x.gain<0?'negative':''}">${money(x.gain)}</strong></div>`).join(''):'<p class="empty">Record a sale to see the matching calculation.</p>'}<a class="link" href="#guide">Read tax notes ↓</a></aside></section>
<section id="guide" class="guide"><div><p class="eyebrow">UK TAX REFERENCE</p><h2>What to retain for each event</h2><p>For a typical listed-company RSU, the vest-date market value is employment income; later price movement is the potential capital gain or loss. This ledger records both without trying to replace your payslip, broker statement or adviser.</p></div><div class="checklist"><p>✓ Grant agreement & vest schedule</p><p>✓ Vest confirmation, units and USD price</p><p>✓ GBP/USD rate and source used</p><p>✓ Payslip / sell-to-cover details</p><p>✓ Trade confirmation and fees</p><p>✓ Prior acquisitions in the same share class</p></div></section>
<section class="sources"><p class="eyebrow">SOURCES & LIMITS</p><p>This tool is a record keeper and calculation aid, not tax advice. It does not calculate Income Tax, NIC or a final CGT liability. Use the actual taxable amount confirmed by your employer and obtain advice for overseas workdays, elections, non-listed shares or complex awards.</p><div><a href="https://www.gov.uk/government/publications/employee-shares-and-securities-further-guidance-hs305-self-assessment-helpsheet/hs305-employment-related-shares-and-securities-further-guidance-2026" target="_blank">HMRC HS305 (2026)</a><a href="https://www.gov.uk/hmrc-internal-manuals/capital-gains-manual/cg51550" target="_blank">HMRC share matching rules</a><a href="https://www.gov.uk/tax-employee-share-schemes" target="_blank">HMRC employee share schemes</a><a href="https://rppaccounts.co.uk/restricted-share-units/" target="_blank">RPP RSU guide</a><a href="https://frazerjames.co.uk/rsus-a-tech-employees-guide-2/" target="_blank">Frazer James guide</a></div></section></main>`;
 document.querySelectorAll('[data-form]').forEach(b=>b.onclick=()=>{document.body.insertAdjacentHTML('beforeend',form(b.dataset.form));const d=document.querySelector('#entryModal');d.showModal();d.querySelector('form').addEventListener('submit',e=>{if(e.submitter.value==='cancel')return;const data=Object.fromEntries(new FormData(e.target));Object.keys(data).forEach(k=>{if(['units','usd','fx','withheld','incomeTax','nic','fees'].includes(k))data[k]=num(data[k])});data.id=crypto.randomUUID();if(data.grantId===undefined&&b.dataset.form==='vest')data.grantId='manual';state[`${b.dataset.form}s`].push(data);save();render();});});
 document.querySelectorAll('[data-delete]').forEach(b=>b.onclick=()=>{const [type,id]=b.dataset.delete.split(':');state[`${type}s`]=state[`${type}s`].filter(x=>x.id!==id);save();render();});
 document.querySelector('#company').onchange=e=>{state.company=e.target.value;save()}; document.querySelector('#ticker').onchange=e=>{state.ticker=e.target.value;save()};
 document.querySelector('[data-action="reset"]').onclick=()=>{if(confirm('Reset all ledger data to the sample?')){state=structuredClone(example);save();render();}};
 document.querySelector('[data-action="export"]').onclick=()=>{const rows=[['type','date','tax_year','units','usd_price','gbp_per_usd','gbp_value_or_proceeds','fees_or_tax','notes'],...state.grants.map(x=>['grant',x.date,taxYear(x.date),x.units,'','','','',x.note]),...state.vests.map(x=>['vest',x.date,taxYear(x.date),x.units,x.usd,x.fx,vestValue(x),num(x.incomeTax)+num(x.nic)+num(x.fees),x.source]),...state.sales.map(x=>['sale',x.date,taxYear(x.date),x.units,x.usd,x.fx,x.units*gbp(x.usd,x.fx)-num(x.fees),x.fees,x.note])];const csv=rows.map(r=>r.map(x=>`"${String(x??'').replaceAll('"','""')}"`).join(',')).join('\n');const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([csv],{type:'text/csv'}));a.download='rsu-ledger-uk.csv';a.click();URL.revokeObjectURL(a.href);};
}
render();
